openapi: 3.0.3
info:
  version: 1.0.0
  title: Organizations API
  description:
    $ref: './docs/api.md'
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
security:
  - bearer: []
tags:
  - name: orgs
    x-displayName: Организации
  - name: members
    x-displayName: Сотрудники
  - name: invitations
    x-displayName: Приглашения
  - name: roles
    x-displayName: Роли
  - name: error-codes
    x-displayName: Коды ошибок
    description:
      $ref: './docs/error-codes.md'
paths:
  /user/membership:
    $ref: ./paths/membership.yaml
  /user/membership/{orgId}:
    $ref: ./paths/orgMembership.yaml
  /user/context:
    $ref: ./paths/context.yaml
  /orgs:
    $ref: ./paths/orgs.yaml
  /orgs/{orgId}:
    $ref: ./paths/org.yaml
  /orgs/{orgId}/roles:
    $ref: ./paths/roles.yaml
  /orgs/{orgId}/roles/{roleId}:
    $ref: ./paths/role.yaml
  /orgs/{orgId}/members:
    $ref: ./paths/members.yaml
  /orgs/{orgId}/members/{userId}:
    $ref: ./paths/member.yaml
  /orgs/{orgId}/members/{userId}/roles:
    $ref: ./paths/memberRoles.yaml
  /orgs/{orgId}/members/{userId}/roles/{memberRoleId}:
    $ref: ./paths/memberRole.yaml
  /orgs/{orgId}/invitations:
    $ref: ./paths/invitations.yaml
  /orgs/{orgId}/invitations/{invitationId}:
    $ref: ./paths/invitation.yaml
components:
  securitySchemes:
    bearer:
      $ref: './components/security-schemes/Bearer.yaml'
